# Generated by Django 4.1.4 on 2023-01-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='img',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
